name: Update package

on:
  workflow_dispatch:

jobs:
  push:
    outputs:
      tag: ${{ steps.latest_tag.outputs.tag }}
    name: push to package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: get latest tag
      id: latest_tag
      uses: WyriHaximus/github-action-get-previous-tag@v1

    - name: set tag
      id: parsed_tag
      run: |
        version=${{ steps.latest_tag.outputs.tag }}
        echo "::set-output name=tag::${version:1}"

    - name: push
      uses: nkoppel/push-files-to-another-repository@v1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN }}
      with:
        commit-email: v3ak6xhthk@gmail.com
        source-files: ansi-render.typ LICENSE README.md typst.toml
        destination-username: ${{ github.repository_owner }}
        destination-repository: packages
        destination-directory: packages/preview/ansi-render/${{ steps.parsed_tag.outputs.tag }}
        destination-branch: main
