name: Update package

# push a new tag before running this action
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push:
    name: push to package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: get latest tag
      id: latest_tag
      uses: WyriHaximus/github-action-get-previous-tag@v1

    - name: set tag
      id: parsed_tag
      run: |
        version=${{ steps.latest_tag.outputs.tag }}
        echo "tag=${version:1}" >> $GITHUB_OUTPUT

    - name: push
      uses: nkoppel/push-files-to-another-repository@v1.1.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.REPO_PAT }}
      with:
        commit-email: v3ak6xhthk@gmail.com
        source-files: ansi-render.typ CHANGELOG.md LICENSE README.md typst.toml
        destination-username: ${{ github.repository_owner }}
        destination-repository: packages
        destination-directory: packages/preview/ansi-render/${{ steps.parsed_tag.outputs.tag }}
        destination-branch: main
